sudo: false
dist: trusty
language: node_js

notifications:
  email:
    on_success: never
    on_failure: always

script:
  - chmod +x travis_deploy_prep.sh
  - ./travis_deploy_prep.sh

deploy:
  provider: pages
  github_token: $PUB_REP_TOKEN
  skip_cleanup: true
  on:
    branch: master
