language: node_js
node_js:
  - "node"

notifications:
  email:
    on_success: never
    on_failure: always

before_script:
  - npm install dotenv --save
  - npm install tape --save
  - npm install @mapbox/togeojson --save

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $PUB_REP_TOKEN
  on:
    branch: gh-pages
