sudo: false
dist: trusty
language: node_js
node_js:
  - "node"

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - npm install tape --save
  - npm install @mapbox/togeojson --save

script:
  - node_modules/tape/bin/tape test/gpx_to_geojson.js
  - chmod +x test/deploy_prep.sh
  - test/deploy_prep.sh

deploy:
  provider: pages
  github_token: $PUB_REP_TOKEN
  skip_cleanup: true
  on:
    branch: master
