sudo: false
dist: trusty
language: node_js
node_js:
  - "node"

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - npm install tape --save
  - npm install @mapbox/togeojson --save
  - npm install simplify-geojson --save
  - npm install @mapbox/geojson-merge --save

script:
  - node_modules/tape/bin/tape test/gpx_to_geojson.js
  - node_modules/\@mapbox/geojson-merge/geojson-merge tracks/geojson/hike/*simple.geojson >tracks/geojson/Overview_hike.geojson
  - node_modules/\@mapbox/geojson-merge/geojson-merge tracks/geojson/bike/*simple.geojson >tracks/geojson/Overview_bike.geojson
  - node_modules/\@mapbox/geojson-merge/geojson-merge tracks/geojson/ski/*simple.geojson >tracks/geojson/Overview_ski.geojson
  - node_modules/\@mapbox/geojson-merge/geojson-merge tracks/geojson/run/*simple.geojson >tracks/geojson/Overview_run.geojson
  - chmod +x test/deploy_prep.sh
  - test/deploy_prep.sh

deploy:
  provider: pages
  github_token: $PUB_REP_TOKEN
  skip_cleanup: true
  on:
    branch: master
