#!/usr/bin/python
# -*- coding: utf-8 -*-
#-------------------------------------------------------------------------------
#
# DESCRIPTION
#    Ensure GPX files have tracks no routes, no unnecessary timing info on
#    tracks, and no unnecessary precision on elevation or track points
#    Used primarily on synthetic tracks generated by mapping apps
#
# EXAMPLES
#    python gpx_trim.py tracks/tim/3_gpx/vehicle/CAR_Istria_Day*
#
# IMPLEMENTATION
#    Author       Tim Smith
#    Copyright    Copyright (c) Tim Smith
#    Licence      GNU General Public License
#
#-------------------------------------------------------------------------------
import os
import pathlib
import fnmatch
import gpxpy
import re
import argparse
import datetime


# Instantiate the parser
parser = argparse.ArgumentParser(description='Trim the GPX track in points and precision.')
# Set up the argument defaults
defaults = dict(dryrun=False,time=False,elevation=False,verbose=False)
parser.set_defaults(**defaults)
# Parse the command line
parser.add_argument("files", help="individual gpx filenames [filenames]", nargs="+")
parser.add_argument('-d', '--dryrun',    action='store_true', help='Dont actually update files')
parser.add_argument('-e', '--elevation', action='store_true', help='Round elevation info in tracks')
parser.add_argument('-o', '--outdir',    dest='outdir',       help='Alterntive file for output in avoiding overwrite')
parser.add_argument('-p', '--precision', type=int,            help='Round lat/lon to this number of decimal places')
parser.add_argument('-s', '--simplify',  dest='simplify',     help='Apply simplification (or not)')
parser.add_argument('-t', '--time',      action='store_true', help='Drop timing info from tracks')
parser.add_argument('-v', '--verbose',   action='store_true', help='Turn on verbose output')
args = parser.parse_args()
print(">>> Cmd line: process files ({})".format(args.files))
print(">>> Cmd line: apply simplify ({}), drop timing ({}), round elevations ({})".format(args.simplify,args.time,args.elevation))
print(">>> Cmd line: round elevations ({}), round lat/lon ({})".format(args.elevation,args.precision))
print(">>> Cmd line: rename output ({}), verbose ({})".format(args.outdir,args.verbose))

VERBOSE = True if args.verbose == True else False

dirlist = ['bike','hike','run','swim','ski','skiclimb']

# Expand any directories passed on the command line into a list of files
fpaths = []
for fpath in args.files:
    if os.path.isfile(fpath):
        fpaths.append(fpath)
    elif os.path.isdir(fpath):
        mpaths = [os.path.join(dp, f) for dp, dn, fn in os.walk(os.path.expanduser(fpath)) for f in fn]
        # Retain only GPX files from the mpaths list
        fpaths = [ file for file in mpaths if file.endswith('.gpx') ]

for fpath in fpaths:
    modified = False
    try:
        gpx = gpxpy.parse(open(fpath,'r'))
    except:
        print("ERROR: Error trying to parse {}".format(fpath))
    bname = os.path.basename(fpath)
    fname = os.path.splitext(bname)[0]
    if VERBOSE : print("INFO: Processing {0:48s}".format(fname))
    if VERBOSE : print("INFO:  (START) GPX file contains {} tracks, {} waypoints, {} routes, {} points".format(len(gpx.tracks),len(gpx.waypoints),len(gpx.routes),gpx.get_track_points_no()))

    # Check the file metadata block
    if gpx.name is None:
        gpx.name = fname
        print("INFO:  > Adding file name field {}".format(fname))
        modified = True

    if len(gpx.routes) > 0:
        # Convert routes into tracks
        print("INFO:  > Converting routes into tracks")
        for r,route in enumerate(gpx.routes):
            gpx.tracks.append(gpxpy.gpx.GPXTrack())
            gpx.tracks[r].segments.append(gpxpy.gpx.GPXTrackSegment())
            gpx.tracks[r].segments[0].points.extend(route.points)
        # Drop the original routes
        gpx.routes = []
        modified = True

    if len(gpx.tracks) > 0:
        #print(gpx.get_elevation_extremes())
        # Simplify tracks by removing unnecessary points
        if args.simplify == True:
            print("INFO:  > Simplify tracks")
            gpx.simplify(max_distance=10)
            modified = True
        for track in gpx.tracks:
            #track.remove_elevation()
            if VERBOSE : print("INFO:  Track contains {} segments".format(len(track.segments)))
            # Drop the point timing information
            if track.has_times():
                if args.time == True:
                    print("INFO:  > Drop timing info from tracks")
                    track.remove_time()
                    modified = True
            if args.precision:
                print("INFO:  > Using a precision of {} decimal places for coordinate trimming".format(args.precision))
                for segment in track.segments:
                    for point in segment.points:
                        # Drop precision on lat/lon
                        point.latitude = round(point.latitude,args.precision)
                        point.longitude = round(point.longitude,args.precision)
            if args.elevation == True:
                print("INFO:  > Round elevation info in tracks")
                for segment in track.segments:
                    for point in segment.points:
                        # Drop precision on elevation
                        if point.elevation != None :
                            point.elevation = int(point.elevation)
                modified = True
            # Check the track metadata block
            tname = track.name
            if tname != fname:
                print("INFO:  >> Updating (file {}) NAME from ({}) to ({})".format(bname,tname,fname))
                track.name = fname
                modified = True
            if track.comment is None:
                print("INFO:  >> Adding track comment field")
                if gpx.time != None :
                    track.comment = str(gpx.time.date())
                else:
                    track.comment = "1970-01-01"
                modified = True
            if track.type is None:
                print("INFO:  >> Adding track type field")
                try:
                    trktype = pathlib.Path(fpath).parts[-2]
                except:
                    trktype = "UNKNOWN"
                if trktype in dirlist :
                    track.type = trktype
                else :
                    track.type = "Velomobile"
                modified = True

    if VERBOSE : print("INFO:  (END) GPX file contains {} tracks, {} waypoints, {} routes, {} points".format(len(gpx.tracks),len(gpx.waypoints),len(gpx.routes),gpx.get_track_points_no()))

    # Write out any changes
    if modified:
        if args.outdir:
            if pathlib.Path(str(args.outdir)).is_dir():
                outfile = args.outdir + "/" + pathlib.Path(fpath).name
            else:
                outfile = args.outdir
        else:
            outfile = fpath
        # Default indentation for PP is 2 spaces, no extra action required
        newtree = gpx.to_xml(prettyprint=True)
        print("INFO: Writing out new content to {}".format(outfile))
        if args.dryrun == False :
            with open(outfile, "w") as f:
                f.write(newtree)
