name: Generate Aggregate Deploy
on: [push]

jobs:
  greet:
    name: Greeting
    runs-on: macos-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Tim'
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
  build:
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      #- name: Use local my-action
      #  uses: ./.github/actions/my-action
