name: MapTracks Build
on:
  push:
    branches:
      - master

jobs:
  GeoJsonBuild:
    name: Generate Aggregate Deploy
    runs-on: macos-latest
    outputs:
      signal: ${{ steps.chain.outputs.status }}
    steps:
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        #--- Next Step
      - name: Install GDAL for gpx transformations
        run: brew install gdal
        #--- Next Step
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        #--- Next Step
      - name: Generate new GeoJson files from GPX files
        run: ./scripts/generate_geojson.sh
        #--- Next Step
      - name: Commit and push to Master
        id: chain
        env:
          commit_mess: ${{ github.event.head_commit.message }}
        run: |
          tile_run=$(scripts/push_geojsons.sh)
          echo "::set-output name=status::$tile_run"
        #--- Next Step
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          exclude_assets: '.github,scripts,tracks/3_gpx'
          allow_empty_commit: true
          commit_message: ${{ github.event.head_commit.message }}
          enable_jekyll: true

  RenewTileset:
    name: Recreate the MapBox tileset
    needs: GeoJsonBuild
    if: contains(needs.GeoJsonBuild.outputs.signal, 'generate')
    runs-on: macos-latest
    steps:
        #--- Next Step
        #--- Temporarily specify a version to avoid picking up Python 3.10, since rasterio and pyrsistent arent ready yet
        #--- Check https://www.wheelodex.org/projects/rasterio/ to see if there is a 3.10 version
        #--- CHeck https://www.wheelodex.org/projects/pyrsistent/ to see if there is a 3.10 version
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
        #--- Next Step
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        #--- Next Step
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        #--- Next Step
      - name: Install MapBox tileset commands
        run: |
          brew install gdal
          pip install mapbox-tilesets
        #--- Next Step
      - name: Build MapBox tileset
        env:
          tileset_api: ${{ secrets.TILESET_CREATOR }}
        run: ./scripts/deploy_tileset.sh
          #-- run: ./scripts/deploy_tileset.sh -f true
