name: MapTracks Build
on: [push]

jobs:
  build:
    name: Generate Aggregate Deploy
    runs-on: macos-latest
    steps:
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install GDAL for gpx transformations
        run: brew install gdal

      - name: Install MapBox tileset commands
        run: pip install mapbox-tilesets

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Generate new GeoJson files from GPX files
        run: ./scripts/generate_geojson.sh

      - name: Check
        run: ls -l tracks/1_display/

      - name: Ensure GPX files arent loaded to Pages
        run: |
          git rm -rq tracks/1_display/*.geojson2
          git rm -rq tracks/3_gpx
          git commit -q -m "Dropped raw GPX files"

        #- name: Build MapBox tileset
        #run: ./scripts/deploy_tileset.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.0-8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          exclude_assets: '.github,tracks/3_gpx'
          allow_empty_commit: true
          commit_message: ${{ github.event.head_commit.message }}
          enable_jekyll: true
