name: MapTrack Build
on: [push]

jobs:
  build:
    name: Generate Aggregate Deploy
    runs-on: macos-latest
    steps:
      - name: Install GDAL for gpx transformations
        run: brew install gdal

      - name: Install MapBox tileset commands
        run: pip install mapbox-tilesets

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Generate new GeoJson files from GPX files
        run: ./scripts/generate_geojson.sh

      - name: Check
        run: ls -l tracks/1_display/

        #- name: Build MapBox tileset
        #run: ./scripts/deploy_tileset.sh

        #- name: Deploy on GitHub Pages
        #run: ./scripts/deploy_travis_prep.sh
