# Simple workflow for deploying static content to GitHub Pages
# For action latest versions check: https://github.com/actions/starter-workflows/blob/main/pages/static.yml
name: PagesDeploy
on:
  # Allows to be run manually from the Actions tab (or a CLI/API dispatch)
  workflow_dispatch:
    inputs:
      caller:
        description: 'Name of commit which triggered original workflow'
        required: true
        default: 'COMMIT'
  # Runs on pushes targeting the www directory
  push:
    paths:
      - 'www/**'

run-name: Pages Deploy for øø ${{ github.event.inputs.caller || github.event.head_commit.message }} by @${{ github.actor }}

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          sparse-checkout: www
      - name: Catchup with changes commited earlier in workflow
        run: git pull --rebase=false
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload from web directory
          path: 'www'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
