name: PullStravaData
on:
  # Nightly cron job
  schedule:
    - cron: 42 19 * * *
  # Allows to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACTION_PERSONAL_ACCESS_TOKEN }}
        #--- Next Step
      - name: Install GPX manipulation commands
        run: |
          sudo apt-get install -y python3-gpxpy
          sudo apt-get install -y python3-numpy
        #--- Next Step
      - name: Fetch Data through Strava API
        run: ./scripts/pull_strava_data.py
        env:
          CONF_CLIENT_ID: ${{ secrets.STRAVA_client_id }}
          CONF_CLIENT_SECRET: ${{ secrets.STRAVA_client_secret }}
          CONF_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        #--- Next Step
      - name: Segment climb/descend tracks
        run: |
          echo ">>> To Segment List"
          git -c core.quotePath=false status --porcelain tracks/3_gpx | awk '{print $2}'
          echo ">>> Segmentation"
          git -c core.quotePath=false status --porcelain tracks/3_gpx | awk '{print $2}' | xargs -n 20 scripts/segment_climb_descent.py
        #--- Next Step
      - name: Commit freshly created files
        run: |
          git config --global user.email "tim.smith@cern.ch"
          git config --global user.name "Tim Smith"
          git status -s 1>&2
          # Push any modified GPX files
          git add tracks/3_gpx 1>&2
          git add features 1>&2
          if ! git diff --staged --quiet --exit-code tracks/3_gpx; then
            echo ">>> New GPX files to commit"
            # Commit any modified GPX files
            git status -s 1>&2
            #git commit -m "${{ github.event.head_commit.message }}" 1>&2
            git commit -m "Strava download BOT: adding latest tracks" 1>&2
            git push 1>&2
          else
            echo ">>> No new GPX files to commit"
          fi
          exit 0

