name: PullStravaData
on:
  # Nightly cron job
  schedule:
    - cron: 42 19 * * *
  # Allows to be run manually from the Actions tab
  workflow_dispatch:

run-name: Pull GPXs from Strava, seq ${{ github.run_number }}

jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACTION_PERSONAL_ACCESS_TOKEN }}
        #--- Next Step
      - name: Install GPX manipulation commands
        run: |
          sudo apt-get install -y python3-gpxpy
          sudo apt-get install -y python3-numpy
        #--- Next Step
      - name: Fetch Data through Strava API
        run: ./scripts/pull_strava_data.py
        env:
          STRAVA_TIM_ID: ${{ secrets.STRAVA_client_id }}
          STRAVA_TIM_SECRET: ${{ secrets.STRAVA_client_secret }}
          STRAVA_TIM_REFTOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        #--- Next Step
      - name: Commit freshly created files
        run: |
          git config --global user.email "tim.smith@cern.ch"
          git config --global user.name "Tim Smith"
          git status -s 1>&2
          # Push any modified GPX files
          git add tracks/tim/3_gpx 1>&2
          git add www/features 1>&2
          if ! git diff --staged --quiet --exit-code tracks/tim/3_gpx; then
            echo ">>> New GPX files to commit"
            # Commit any modified GPX files
            git status -s 1>&2
            #git commit -m "${{ github.event.head_commit.message }}" 1>&2
            git commit -m "Strava BOT: downloading GPX tracks" 1>&2
            git push 1>&2
          else
            echo ">>> No new GPX files to commit"
          fi
          exit 0

