name: PullStravaData
on:
  # Nightly cron job
  #schedule:
  #  - cron: 25 17 * * 0-6
  # Allows to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Fetch Data through Strava API
        run: ./scripts/PullStravaData.py
        env:
          CONF_METHOD: POST
          CONF_CLIENT_ID: ${{ secrets.STRAVA_client_id }}
          CONF_CLIENT_SECRET: ${{ secrets.STRAVA_client_secret }}
          CONF_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
