name: MapBoxTilesDeploy
on:
  # Reusable workflow to be called from MapTracksDeploy
  workflow_call:

  # Allows to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  # Deployment job
  RenewTileset:
    name: Recreate the MapBox tileset
    runs-on: macos-latest
    steps:
        #--- Next Step
        #--- Temporarily specify a version to avoid picking up Python 3.10, since rasterio and pyrsistent arent ready yet
        #--- Check https://www.wheelodex.org/projects/rasterio/ to see if there is a 3.10 version
        #--- CHeck https://www.wheelodex.org/projects/pyrsistent/ to see if there is a 3.10 version
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
        #--- Next Step
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        #--- Next Step
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        #--- Next Step
      - name: Install MapBox tileset commands
        run: |
          brew install gdal
          pip install mapbox-tilesets
        #--- Next Step
      - name: Build MapBox tileset
        env:
          tileset_api: ${{ secrets.TILESET_CREATOR }}
        run: scripts/tileset_deploy.sh -d true
          #-- run: scripts/tileset_deploy.sh -f true

