name: MapTracksDeploy
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows to be run manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build GeoJSON files from any newly committed GPX files
  GeoJsonBuild:
    name: Generate Aggregate Deploy
    runs-on: macos-latest
    outputs:
      signal: ${{ steps.chain.outputs.run_commit }}
    steps:
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
        #--- Next Step
      - name: Install GDAL for gpx transformations
        run: brew install gdal
        #--- Next Step
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        #--- Next Step
      - name: Generate new GeoJson files from GPX files
        run: ./scripts/generate_geojson.sh
        #--- Next Step
      - name: Signal new GeoJson files built
        id: chain
        run: |
          if ! git diff --quiet --exit-code tracks/1_display; then
            echo "::set-output name=run_commit::true"
          else
            echo "::set-output name=run_commit::false"

  # Commit any newly built GeoJSON files
  CommitGeoJSON:
    needs: GeoJsonBuild
    runs-on: macos-latest
    if: ${{ steps.chain.outputs.run_commit == true }}
    steps:
      - name: Commit and push to Master
        run: |
          # Push the modified GeoJSON files
          git add tracks/1_display 1>&2
          git add tracks/2_geojson 1>&2
          git status -s 1>&2
          git commit -m ${{ github.event.head_commit.message }} 1>&2
          git push 1>&2

  # Deploy to GitHub Pages MapTracks website
  DeployPages:
    needs: CommitGeoJSON
    runs-on: macos-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  # Recreate the MapBox tileset
  TilesDeploy:
    needs: CommitGeoJSON
    uses: ./.github/workflows/TilesDeploy.yml

