name: TrimTempTracks
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
    paths:
      - 'scripts/**'
      - 'tracks/tim/6_temp/**'

  # Allows to be run manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

run-name: Trim GPXs for ${{ github.event.head_commit.message }}

jobs:
  # Build GeoJSON files from any newly committed GPX files
  GeoJsonBuild:
    name: Routes_to_Tracks
    runs-on: macos-latest
    steps:
      - name: Set up Python 3.x
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      #--- Prepare prequisite libraries
      - name: Install GPXpy for gpx transformations
        run: pip install gpxpy
      #--- Checkout using PAT rather than default token, so PagesDeploy/push workflow gets triggered
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_ACTION_PERSONAL_ACCESS_TOKEN }}
      #--- First Step
      - name: Trim GPX files from temporary directory 
        run: |
          echo ">>> Trim all temporary GPX files"
          find tracks/tim/6_temp -mindepth 1 -maxdepth 1 -type f -exec python scripts/gpx_trim.py -e -x -p 6 -t {} \;
